image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip
    # To allow building on non-RPi architecture
  - export READTHEDOCS=True
  - cd docs
  - pip install -r requirements.txt && pip install -r ../requirements.txt

run:
  script:
      # Currently in `docs` directory (from `before_script` above)
    - make clean && make html
    - rm -rfv /var/www/dynaikon/dynaikon.com/dynaikontrap-docs/* # -f flag removes error status for non existing files
    - mkdir -p /var/www/dynaikon/dynaikon.com/dynaikontrap-docs # -p flag no error status if directory existing
    - ls -l /var/www/dynaikon/dynaikon.com/dynaikontrap-docs
    - rm -rfv /var/www/dynaikon/dynaikon.com/dynaikontrap-docs/*
    - cp -rv build/html/* /var/www/dynaikon/dynaikon.com/dynaikontrap-docs
    - cp -rv build/html/* "$CI_PROJECT_DIR/"
      # Pipeline debugging
    - tar -czvf "$CI_PROJECT_DIR/docs.tar.gz" build/html/*
    - ls -l "$CI_PROJECT_DIR/"
    - grep -rF 1.3.1 "$CI_PROJECT_DIR/"
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/docs.tar.gz"
  only:
    - tags
