# Version 3.7 is necessary for `numpy` to build correctly
image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  HERMES_ROOT: /var/www/dynaikon/dynaikon.com/dynaikontrap-docs

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  # https://docs.gitlab.com/ee/ci/caching/#cache-python-dependencies
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip
    # To allow building on non-RPi architecture
  - export READTHEDOCS=True
  - cd docs
  - pip install -r requirements.txt && pip install -r ../requirements.txt

run:
  script:
      # Currently in `docs` directory (from `before_script` above)
    - make clean && make html
      # Delete current documentation
      # -f flag removes error status for non existing files
    - rm -rfv "$HERMES_ROOT/*"
      # Copy new documentation
    - cp -rv build/html/* "$HERMES_ROOT"
    - date +"Version $(cat ../VERSION) built at %F-%H%M%S %Z from $CI_COMMIT_SHA" > "$HERMES_ROOT/$CI_COMMIT_SHA/buildinfo"
      # Create tarball at webroot
    - tar -czvf "$HERMES_ROOT/DynAikonTrap-Docs.tar.gz" -C build/html .
      # Create Downloadable Artifact
    - tar -czvf "$CI_PROJECT_DIR/DynAikonTrap-Docs.tar.gz" -C build/html .
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/DynAikonTrap-Docs.tar.gz"
